SIDEBAR = "sidebar"
MAIN_CONTENT = "main-content"
DESTINATIONS_LIST = "destinations-list"
VISIT_ORDER_STORE = "visit-order-store"
SAVE_TRIP_MODAL = "save-trip-modal"
SAVE_TRIP_NAME_INPUT = "save-trip-name-input"
SAVE_TRIP_CONFIRM_BTN = "save-trip-confirm-btn"
SAVE_TRIP_ALERT = "save-trip-alert"
SELECTED_OBJECTS_GROUP = "selected-objects-group"
OPTIMIZE_ROUTE_BTN = "optimize-route-btn"
SAVE_TRIP_BTN = "save-trip-btn"
SHARE_TRIP_BTN = "share-trip-btn"
SHARE_TRIP_TOAST = "share-trip-toast"
LOAD_TRIP_BTN = "load-trip-btn"
LOAD_TRIP_MODAL = "load-trip-modal"
LOAD_TRIP_LIST = "load-trip-list"
USER_SHARED_TRIPS_LIST = "user-shared-trips-list"
START_POINT_DROPDOWN = "start-point-dropdown"
END_POINT_DROPDOWN = "end-point-dropdown"
CLEAR_ALL_BTN = "clear-all-btn"
WARN_MODAL = "warn-modal"
SUCCESS_TOAST = "success-toast"

# Auth IDs
LOGIN_USERNAME = "login-username"
LOGIN_PASSWORD = "login-password"
LOGIN_BUTTON = "login-button"
REGISTER_BUTTON = "register-button"
REGISTER_FIRST_NAME = "register-first-name"
REGISTER_LAST_NAME = "register-last-name"
REGISTER_FIELDS = "register-fields"
LOGOUT_BUTTON = "logout-button"
USER_MENU = "user-menu"
LOGIN_ALERT = "login-alert"
PAGE_CONTENT = "page-content"

# Geolocation
GEOLOCATION = "geolocation"
USER_LOCATION_LAYER = "user-location-layer"

ROUTE_STATS_PANEL = "route-stats-panel"

# Mode toggle
MODE_STORE = "mode-store"
BROWSE_OVERLAY_STORE = "browse-overlay-store"
BROWSE_SAVED_TRIPS_STORE = "browse-saved-trips-store"
BROWSE_SHARED_TRIPS_STORE = "browse-shared-trips-store"
MODE_BTN_EXPLORE = "mode-btn-explore"
MODE_BTN_TRIP = "mode-btn-trip"
MODE_BTN_BROWSE = "mode-btn-browse"
EXPLORE_PANEL = "explore-panel"
TRIP_PANEL = "trip-panel"
BROWSE_PANEL = "browse-panel"
BROWSE_OVERLAY = "browse-overlay"
BROWSE_CLOSE_BTN = "browse-close-btn"
BROWSE_TABS = "browse-tabs"
MY_SAVED_TRIPS_TAB = "my-saved-trips-tab"
USER_SHARED_TRIPS_TAB = "user-shared-trips-tab"
TRIP_STATUS_PANEL = "trip-status-panel"
TRIP_NEXT_VISIT_BTN = "trip-next-visit-btn"

# Landmark reviews
LANDMARK_REVIEW_PANE = "landmark-review-pane"
LANDMARK_REVIEW_CLOSE_BTN = "landmark-review-close-btn"
LANDMARK_REVIEW_STATE_STORE = "landmark-review-state-store"
LANDMARK_REVIEW_TITLE = "landmark-review-title"
LANDMARK_REVIEW_LOCATION = "landmark-review-location"
LANDMARK_REVIEW_STAR_ROW = "landmark-review-star-row"
LANDMARK_REVIEW_TEXT = "landmark-review-text"
LANDMARK_REVIEW_SUBMIT_BTN = "landmark-review-submit-btn"
LANDMARK_REVIEW_SKIP_BTN = "landmark-review-skip-btn"
LANDMARK_REVIEW_ALERT = "landmark-review-alert"

# Active trip (Trip mode)
ACTIVE_TRIP_STORE = "active-trip-store"
TRIP_MODE_LAYER = "trip-mode-layer"
EXPLORE_MAP_CACHE = "explore-map-cache"

# Map layers
ALL_MARKERS_LAYER = "all-markers-layer"
PLANNED_TRIP_MARKERS_LAYER = "planned-trip-markers-layer"
PLANNED_TRIP_POLYLINE_LAYER = "planned-trip-polyline-layer"
LOADED_TRIP_MARKERS_LAYER = "loaded-trip-markers-layer"
LOADED_TRIP_POLYLINE_LAYER = "loaded-trip-polyline-layer"
